- hosts: all
  become: yes
  tasks:
     - name: Disable root login via SSH
       ansible.builtin.lineinfile:
         dest: /etc/ssh/sshd_config
         regexp: "^PermitRootLogin"
         line: "PermitRootLogin no"
       notify: systemctl restart sshd
