- hosts: web
  tasks:
    - name: install httpd package
      package:
        name: httpd
        state: present

    - name: starting httpd service
      service:
        name: httpd
        state: restarted
        enabled: yes

    - name: install php package
      package:
        name: php
        state: latest

    - name: copy config files
      copy:
        src: index.php
        dest: /var/www/html
